import { addAggregate } from './methods/aggregate';
import { addAll } from './methods/all';
import { addAny } from './methods/any';
import { addAverage } from './methods/average';
import { addConcatLt } from './methods/concatLt';
import { addContains } from './methods/contains';
import { addCount } from './methods/count';
import { addDefaultIfEmpty } from './methods/defaultIfEmpty';
import { addDistinct } from './methods/distinct';
import { addElementAt } from './methods/elementAt';
import { addElementAtOrDefault } from './methods/elementAtOrDefault';
import { addExcept } from './methods/except';
import { addFirst } from './methods/first';
import { addFirstOrDefault } from './methods/firstOrDefault';
import { addGroupBy } from './methods/groupBy';
import { addIntersect } from './methods/intersect';
import { addJoinLt } from './methods/joinLt';
import { addLast } from './methods/last';
import { addLastOrDefault } from './methods/lastOrDefault';
import { addMax} from './methods/max';
import { addMin } from './methods/min';
import { addOrderBy } from './methods/orderBy';
import { addOrderByDescending } from './methods/orderByDescending';
import { addReverseLt } from './methods/reverseLt';
import { addSelect } from './methods/select';
import { addSelectMany } from './methods/selectMany';
import { addSequenceEqual } from './methods/sequenceEqual';
import { addSingle } from './methods/single';
import { addSingleOrDefault } from './methods/singleOrDefault';
import { addSkip } from './methods/skip';
import { addSum } from './methods/sum';
import { addTake } from './methods/take';
import { addThenBy } from './methods/thenBy';
import { addThenByDescending } from './methods/thenByDescending';
import { addUnion } from './methods/union';
import { addWhere } from './methods/where';
import { addZip } from './methods/zip';

addAggregate();
addAll();
addAny();
addAverage();
addConcatLt();
addContains();
addCount();
addDefaultIfEmpty();
addDistinct();
addElementAt();
addElementAtOrDefault();
addExcept();
addFirst();
addFirstOrDefault();
addGroupBy();
addIntersect();
addJoinLt();
addLast();
addLastOrDefault();
addMax();
addMin();
addOrderBy();
addOrderByDescending();
addReverseLt();
addSelect();
addSelectMany();
addSequenceEqual();
addSingle();
addSingleOrDefault();
addSkip();
addSum();
addTake();
addThenBy();
addThenByDescending();
addUnion();
addWhere();
addZip();